pool:
  vmImage: 'ubuntu-latest'


steps:
- task: SonarQubePrepare@5
  displayName: 'Prepare analysis on SonarQube'
  inputs:
    SonarQube: 'nhsuk-prototype-kit'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'nhsuk-prototype-kit'
    extraProperties: |
        sonar.javascript.lcov.reportPaths=coverage/lcov.info

- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: true
    
- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: 'custom'
    customCommand: run build
    verbose: true

- task: Npm@1
  displayName: 'npm run test'
  inputs:
    command: 'custom'
    customCommand: run test
    verbose: true

- task: SonarQubeAnalyze@5
  displayName: 'Run code analysis' 

- task: SonarQubePublish@5
  displayName: 'Publish quality gate result'
  inputs:
    pollingTimeoutSec: '300'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'

    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'
